# Generated by Django 5.0 on 2023-12-14 04:39

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre.models.play_image_file_path
            ),
        ),
    ]
